In [1]:
import pandas as pd
import numpy as np
import datetime as dt
import matplotlib.pyplot as plt
import pandas.io.data as web
%matplotlib inline

/Library/Python/2.7/site-packages/pandas/io/data.py:33: FutureWarning:
The pandas.io.data module is moved to a separate package (pandas-datareader) and will be removed from pandas in a future version.
After installing the pandas-datareader package (https://github.com/pydata/pandas-datareader), you can change the import ``from pandas.io import data, wb`` to ``from pandas_datareader import data, wb``.
  FutureWarning)

In [2]:
all_data= pd.read_csv('../../../data/third_party_preds/baidu-091915.csv', encoding='cp1252')

In [245]:
all_data['k1 win'] = all_data['Home Win']- (1- all_data['Home Win'])/(all_data['b365H']-1)
all_data['k1 draw'] =all_data['Home Draw']- (1- all_data['Home Draw'])/(all_data['b365D']-1)
all_data['k1 lost'] =all_data['Home Lost']- (1- all_data['Home Lost'])/(all_data['b365A']-1)
result = pd.get_dummies(all_data, columns=['result'])[['result_1', 'result_2', 'result_3']]

In [246]:
#kr = pd.DataFrame((all_data[['k1 win','k1 draw','k1 lost']]).values*result.values, columns=result.columns, index=result.index)
#kr.replace([0.0],[np.nan])
#(all_data[['k1 win','k1 draw','k1 lost','result']])

In [247]:
all_data['k2 win'] = ((all_data['b365H']+1)*all_data['Home Win']- 1)/(all_data['b365H']+1-1)
all_data['k2 draw'] =((all_data['b365D']+1)*all_data['Home Draw']- 1)/(all_data['b365D']+1-1)
all_data['k2 lost'] =((all_data['b365A']+1)*all_data['Home Lost']- 1)/(all_data['b365A']+1-1)
all_data[['b365H','b365D','b365A','Home Win','Home Draw','Home Lost','k2 win','k2 draw','k2 lost','result']]

,b365H,b365D,b365A,Home Win,Home Draw,Home Lost,k2 win,k2 draw,k2 lost,result
0,2.45,3.50,3.00,0.40,0.29,0.31,0.155102,0.087143,0.080000,1
1,1.70,4.00,5.50,0.55,0.27,0.18,0.285294,0.087500,0.030909,1
2,2.50,3.40,3.00,0.39,0.29,0.32,0.146000,0.081176,0.093333,2
3,2.50,3.30,3.10,0.38,0.31,0.31,0.132000,0.100909,0.087419,3
4,2.30,3.25,3.50,0.41,0.31,0.28,0.153478,0.097692,0.074286,3
5,2.30,3.40,3.40,0.41,0.30,0.29,0.153478,0.094118,0.081176,2
6,1.29,6.50,11.00,0.75,0.17,0.08,0.556202,0.042308,-0.003636,3
7,2.00,3.60,4.00,0.49,0.28,0.23,0.235000,0.080000,0.037500,1
8,1.67,4.00,5.75,0.59,0.25,0.16,0.344491,0.062500,0.013913,2
9,3.10,3.30,2.50,0.30,0.31,0.39,0.074194,0.100909,0.146000,3
10,2.15,3.50,3.30,0.43,0.28,0.29,0.164884,0.074286,0.074848,1
11,2.05,3.50,3.60,0.46,0.28,0.26,0.196585,0.074286,0.054444,3
12,2.50,3.50,2.75,0.38,0.28,0.34,0.132000,0.074286,0.100000,2
13,1.50,4.33,6.50,0.63,0.23,0.14,0.383333,0.052171,0.007692,1
14,2.40,3.30,3.00,0.39,0.29,0.32,0.135833,0.074848,0.093333,1
15,19.00,7.00,1.17,0.05,0.15,0.80,0.000000,0.028571,0.629060,3
16,2.63,3.50,2.60,0.38,0.27,0.35,0.144259,0.061429,0.100000,3
17,2.00,3.50,3.75,0.47,0.28,0.25,0.205000,0.074286,0.050000,1
18,1.73,4.00,4.50,0.56,0.26,0.18,0.305665,0.075000,-0.002222,1
19,2.38,3.00,3.40,0.40,0.32,0.28,0.147899,0.093333,0.068235,2
20,8.00,4.75,1.40,0.11,0.23,0.66,-0.001250,0.067895,0.417143,2
21,1.85,3.30,4.75,0.50,0.30,0.20,0.229730,0.087879,0.031579,1
22,2.10,3.10,4.00,0.44,0.31,0.25,0.173333,0.087419,0.062500,1
23,2.25,3.10,3.50,0.42,0.31,0.27,0.162222,0.087419,0.061429,3
24,2.15,3.10,3.75,0.43,0.30,0.27,0.164884,0.074194,0.075333,1
25,2.10,3.10,4.00,0.45,0.30,0.25,0.188095,0.074194,0.062500,2
26,1.70,3.60,5.50,0.57,0.26,0.17,0.317059,0.054444,0.019091,3
27,1.67,3.50,6.00,0.54,0.29,0.17,0.264551,0.087143,0.031667,1
28,2.05,3.30,3.80,0.46,0.28,0.26,0.196585,0.061818,0.065263,2
29,2.60,3.10,2.90,0.36,0.32,0.32,0.113846,0.100645,0.085517,1
30,1.06,15.00,26.00,0.89,0.08,0.03,0.786226,0.018667,-0.007308,1
31,1.50,4.33,6.50,0.62,0.24,0.14,0.366667,0.064480,0.007692,2
32,7.00,3.75,1.57,0.14,0.27,0.59,0.017143,0.075333,0.328854,3
33,2.00,3.40,4.00,0.48,0.29,0.23,0.220000,0.081176,0.037500,3
34,1.80,3.75,4.33,0.52,0.26,0.22,0.253333,0.062667,0.039861,3
35,2.05,3.10,4.20,0.47,0.30,0.23,0.211463,0.074194,0.046667,3
36,2.00,3.50,3.75,0.49,0.29,0.22,0.235000,0.087143,0.012000,1
37,1.91,3.50,4.00,0.49,0.28,0.23,0.222984,0.074286,0.037500,3
38,1.06,12.00,29.00,0.89,0.08,0.03,0.786226,0.003333,-0.003448,1
39,2.25,3.30,3.30,0.43,0.30,0.27,0.176667,0.087879,0.048788,3
40,1.73,3.75,5.00,0.54,0.28,0.18,0.274104,0.088000,0.016000,1
41,3.75,3.30,2.10,0.26,0.30,0.44,0.062667,0.087879,0.173333,3
42,1.83,3.60,4.33,0.53,0.28,0.19,0.273169,0.080000,0.002933,1
43,4.50,3.50,1.83,0.20,0.30,0.50,0.022222,0.100000,0.226776,3
44,1.40,4.50,8.50,0.67,0.22,0.11,0.434286,0.046667,0.005294,2
45,1.95,3.40,4.00,0.50,0.29,0.21,0.243590,0.081176,0.012500,1
46,2.00,3.50,3.75,0.47,0.28,0.25,0.205000,0.074286,0.050000,2
47,4.33,3.40,1.91,0.22,0.29,0.49,0.039861,0.081176,0.222984,3
48,1.91,3.60,4.00,0.51,0.28,0.21,0.253455,0.080000,0.012500,1

In [248]:
all_data['select k2'] = all_data[['k2 win','k2 draw','k2 lost']].max(axis=1)
(all_data['select k2']).head()

0    0.155102
1    0.285294
2    0.146000
3    0.132000
4    0.153478
Name: select k2, dtype: float64

In [249]:
result2 = (all_data[['b365H','b365D','b365A']]-1)
all_data[['b365H-1','b365D-1','b365A-1']]= result2
result2.head()

   b365H  b365D  b365A
0   1.45   2.50    2.0
1   0.70   3.00    4.5
2   1.50   2.40    2.0
3   1.50   2.30    2.1
4   1.30   2.25    2.5

In [250]:
odds =pd.DataFrame(result2.values*result.values, columns=result2.columns, index=result2.index)
odds =odds.replace([0.0],[-1])
all_data[['b365H-odds','b365D-odds','b365A-odds']]= odds
odds.head()

   b365H  b365D  b365A
0   1.45   -1.0   -1.0
1   0.70   -1.0   -1.0
2  -1.00    2.4   -1.0
3  -1.00   -1.0    2.1
4  -1.00   -1.0    2.5

In [251]:
#all_data['Ewin']=all_data['b365H']*all_data['Home Win']+all_data['Home Win']-1
#all_data['Edraw']=all_data['b365D']*all_data['Home Draw']+all_data['Home Draw']-1
#all_data['Elost']=all_data['b365A']*all_data['Home Lost']+all_data['Home Lost']-1
#e =pd.DataFrame(all_data[['Ewin','Edraw','Elost']].values*all_data[['k2 win','k2 draw','k2 lost']].values, columns=odds.columns, index=odds.index)
#all_data[['b365H-e','b365D-e','b365A-e']]= e
#e

In [252]:
#Best: For each game, we place a unit bet on the outcome with maximum Di, if that
#Di > 0. This is similar to Positive, but places a bet on only one outcome per game.
#Di=Pi-1/odds
all_data['Di win'] = all_data['Home Win']- 1/all_data['b365H']
all_data['Di draw'] = all_data['Home Draw']- 1/all_data['b365D']
all_data['Di lost'] = all_data['Home Lost']- 1/all_data['b365A']

all_data['select Di'] = all_data[['Di win','Di draw','Di lost']].max(axis=1)
(all_data['select Di']).head()

0    0.004286
1    0.020000
2   -0.004118
3    0.006970
4    0.002308
Name: select Di, dtype: float64

In [253]:
all_data['select p'] = all_data[['Home Win','Home Draw','Home Lost']].max(axis=1)
(all_data['select p']).head()

0    0.40
1    0.55
2    0.39
3    0.38
4    0.41
Name: select p, dtype: float64

In [272]:
#all_data['k2 win select'] = all_data.apply(lambda x : x['k2 win'] if x['k2 win'] >= x['select k2'] and ((x['select k2'] - x['k2 win']) <= 0.05) else 0 , axis=1)
#all_data['k2 win select'] = np.where((all_data['k2 win'] >= all_data['select k2']) | ((all_data['select k2']-all_data['k2 win'])<=0.051)
#                     , all_data['k2 win'], np.nan)
#all_data['k2 draw select'] = np.where((all_data['k2 draw'] >= all_data['select k2']) | ((all_data['select k2']-all_data['k2 draw'])<=0.051)
#                     , all_data['k2 draw'], np.nan)
#all_data['k2 lost select'] = np.where((all_data['k2 lost'] >= all_data['select k2']) | ((all_data['select k2']-all_data['k2 lost'])<=0.051)
#                     , all_data['k2 lost'], np.nan)
#all_data['k2 win select'] = np.where((all_data['k2 win'] > all_data['select k2'])
#                     , all_data['k2 win'], np.nan)
#all_data['k2 draw select'] = np.where((all_data['k2 draw'] > all_data['select k2'])
#                     , all_data['k2 draw'], np.nan)
#all_data['k2 lost select'] = np.where((all_data['k2 lost'] > all_data['select k2'])
#                     , all_data['k2 lost'], np.nan)
#all_data['win select'] = np.where((all_data['k1 win'] > 0) , all_data['k1 win'], np.nan)
#all_data['draw select'] = np.where((all_data['k1 draw'] > 0), all_data['k1 draw'], np.nan)
#all_data['lost select'] = np.where((all_data['k1 lost'] > 0), all_data['k1 lost'], np.nan)
all_data['win select'] = np.where((all_data['Home Win']*all_data['b365H'] >= 1.1) & ((all_data['select p'])>0)
                    , 1+all_data['k1 win'], np.nan)
all_data['draw select'] = np.where((all_data['Home Draw']*all_data['b365D'] >= 1.1) & ((all_data['select p'])>0)
                     , 1+all_data['k1 draw'], np.nan)
all_data['lost select'] = np.where((all_data['Home Lost']*all_data['b365A'] >= 1.1) & ((all_data['select p'])>0)
                     , 1+all_data['k1 lost'], np.nan)

In [273]:
k2_res =all_data[['win select','draw select', 'lost select']]
k2_res =k2_res.fillna(0)
k2_res.head()

   win select  draw select  lost select
0           0            0            0
1           0            0            0
2           0            0            0
3           0            0            0
4           0            0            0

In [274]:
odds.head(10)

   b365H  b365D  b365A
0   1.45   -1.0   -1.0
1   0.70   -1.0   -1.0
2  -1.00    2.4   -1.0
3  -1.00   -1.0    2.1
4  -1.00   -1.0    2.5
5  -1.00    2.4   -1.0
6  -1.00   -1.0   10.0
7   1.00   -1.0   -1.0
8  -1.00    3.0   -1.0
9  -1.00   -1.0    1.5

In [275]:
act_res =pd.DataFrame(odds.values*k2_res.values, columns=odds.columns, index=odds.index)
all_data[['b365H-act_res','b365D-act_res','b365A-act_res']]= act_res
act_res.head()

   b365H  b365D  b365A
0      0     -0     -0
1      0     -0     -0
2     -0      0     -0
3     -0     -0      0
4     -0     -0      0

In [276]:
all_data['total'] = act_res['b365H']+act_res['b365D']+act_res['b365A']

In [277]:
r = all_data['total']

In [278]:
r.sum()

-2.0333766233766233

In [279]:
all_data[['result','b365H-act_res','b365D-act_res','b365A-act_res','Home Win', 'Home Draw','Home Lost','win select','draw select', 'lost select','k1 win','k1 draw','k1 lost']]

,result,b365H-act_res,b365D-act_res,b365A-act_res,Home Win,Home Draw,Home Lost,win select,draw select,lost select,k1 win,k1 draw,k1 lost
0,1,0,-0.000000,-0,0.40,0.29,0.31,NaN,NaN,NaN,-0.013793,0.006000,-0.035000
1,1,0,-0.000000,-0,0.55,0.27,0.18,NaN,NaN,NaN,-0.092857,0.026667,-0.002222
2,2,-0,0.000000,-0,0.39,0.29,0.32,NaN,NaN,NaN,-0.016667,-0.005833,-0.020000
3,3,-0,-0.000000,0,0.38,0.31,0.31,NaN,NaN,NaN,-0.033333,0.010000,-0.018571
4,3,-0,-0.000000,0,0.41,0.31,0.28,NaN,NaN,NaN,-0.043846,0.003333,-0.008000
5,2,-0,0.000000,-0,0.41,0.30,0.29,NaN,NaN,NaN,-0.043846,0.008333,-0.005833
6,3,-0,-1.019091,0,0.75,0.17,0.08,NaN,1.019091,NaN,-0.112069,0.019091,-0.012000
7,1,0,-0.000000,-0,0.49,0.28,0.23,NaN,NaN,NaN,-0.020000,0.003077,-0.026667
8,2,-0,0.000000,-0,0.59,0.25,0.16,NaN,NaN,NaN,-0.021940,0.000000,-0.016842
9,3,-0,-0.000000,0,0.30,0.31,0.39,NaN,NaN,NaN,-0.033333,0.010000,-0.016667
10,1,0,-0.000000,-0,0.43,0.28,0.29,NaN,NaN,NaN,-0.065652,-0.008000,-0.018696
11,3,-0,-0.000000,0,0.46,0.28,0.26,NaN,NaN,NaN,-0.054286,-0.008000,-0.024615
12,2,-0,0.000000,-0,0.38,0.28,0.34,NaN,NaN,NaN,-0.033333,-0.008000,-0.037143
13,1,0,-0.000000,-0,0.63,0.23,0.14,NaN,NaN,NaN,-0.110000,-0.001231,-0.016364
14,1,0,-0.000000,-0,0.39,0.29,0.32,NaN,NaN,NaN,-0.045714,-0.018696,-0.020000
15,3,-0,-0.000000,0,0.05,0.15,0.80,NaN,NaN,NaN,-0.002778,0.008333,-0.376471
16,3,-0,-0.000000,0,0.38,0.27,0.35,NaN,NaN,NaN,-0.000368,-0.022000,-0.056250
17,1,0,-0.000000,-0,0.47,0.28,0.25,NaN,NaN,NaN,-0.060000,-0.008000,-0.022727
18,1,0,-0.000000,-0,0.56,0.26,0.18,NaN,NaN,NaN,-0.042740,0.013333,-0.054286
19,2,-0,0.000000,-0,0.40,0.32,0.28,NaN,NaN,NaN,-0.034783,-0.020000,-0.020000
20,2,-0,0.000000,-0,0.11,0.23,0.66,NaN,NaN,NaN,-0.017143,0.024667,-0.190000
21,1,0,-0.000000,-0,0.50,0.30,0.20,NaN,NaN,NaN,-0.088235,-0.004348,-0.013333
22,1,0,-0.000000,-0,0.44,0.31,0.25,NaN,NaN,NaN,-0.069091,-0.018571,0.000000
23,3,-0,-0.000000,0,0.42,0.31,0.27,NaN,NaN,NaN,-0.044000,-0.018571,-0.022000
24,1,0,-0.000000,-0,0.43,0.30,0.27,NaN,NaN,NaN,-0.065652,-0.033333,0.004545
25,2,-0,0.000000,-0,0.45,0.30,0.25,NaN,NaN,NaN,-0.050000,-0.033333,0.000000
26,3,-0,-0.000000,0,0.57,0.26,0.17,NaN,NaN,NaN,-0.044286,-0.024615,-0.014444
27,1,0,-0.000000,-0,0.54,0.29,0.17,NaN,NaN,NaN,-0.146567,0.006000,0.004000
28,2,-0,0.000000,-0,0.46,0.28,0.26,NaN,NaN,NaN,-0.054286,-0.033043,-0.004286
29,1,0,-0.000000,-0,0.36,0.32,0.32,NaN,NaN,NaN,-0.040000,-0.003810,-0.037895
30,1,0,-1.014286,-0,0.89,0.08,0.03,NaN,1.014286,NaN,-0.943333,0.014286,-0.008800
31,2,-0,0.000000,-0,0.62,0.24,0.14,NaN,NaN,NaN,-0.140000,0.011772,-0.016364
32,3,-0,-0.000000,0,0.14,0.27,0.59,NaN,NaN,NaN,-0.003333,0.004545,-0.129298
33,3,-0,-0.000000,0,0.48,0.29,0.23,NaN,NaN,NaN,-0.040000,-0.005833,-0.026667
34,3,-0,-0.000000,0,0.52,0.26,0.22,NaN,NaN,NaN,-0.080000,-0.009091,-0.014234
35,3,-0,-0.000000,0,0.47,0.30,0.23,NaN,NaN,NaN,-0.034762,-0.033333,-0.010625
36,1,0,-0.000000,-0,0.49,0.29,0.22,NaN,NaN,NaN,-0.020000,0.006000,-0.063636
37,3,-0,-0.000000,0,0.49,0.28,0.23,NaN,NaN,NaN,-0.070440,-0.008000,-0.026667
38,1,0,-0.000000,-0,0.89,0.08,0.03,NaN,NaN,NaN,-0.943333,-0.003636,-0.004643
39,3,-0,-0.000000,0,0.43,0.30,0.27,NaN,NaN,NaN,-0.026000,-0.004348,-0.047391
40,1,0,-0.000000,-0,0.54,0.28,0.18,NaN,NaN,NaN,-0.090137,0.018182,-0.025000
41,3,-0,-0.000000,0,0.26,0.30,0.44,NaN,NaN,NaN,-0.009091,-0.004348,-0.069091
42,1,0,-0.000000,-0,0.53,0.28,0.19,NaN,NaN,NaN,-0.036265,0.003077,-0.053243
43,3,-0,-0.000000,0,0.20,0.30,0.50,NaN,NaN,NaN,-0.028571,0.020000,-0.102410
44,2,-0,0.000000,-0,0.67,0.22,0.11,NaN,NaN,NaN,-0.155000,-0.002857,-0.008667
45,1,0,-0.000000,-0,0.50,0.29,0.21,NaN,NaN,NaN,-0.026316,-0.005833,-0.053333
46,2,-0,0.000000,-0,0.47,0.28,0.25,NaN,NaN,NaN,-0.060000,-0.008000,-0.022727
47,3,-0,-0.000000,0,0.22,0.29,0.49,NaN,NaN,NaN,-0.014234,-0.005833,-0.070440
48,1,0,-0.000000,-0,0.51,0.28,0.21,NaN,NaN,NaN,-0.028462,0.003077,-0.053333

In [732]:
all_data.to_csv('k-baidu-092615.csv')